### ISSUE TITLE
papagayo-ng vs LostMarble Papagayo 2.0?

### ISSUE THREAD

**Issue by pabs3** [morevnaproject-org/papagayo-ng#106]
I noticed that @LostMarble have released a beta of Papagayo 2.0, rewritten in Qt/C++:

https://github.com/LostMoho/Papagayo

Will papagayo-ng be rebased on top of this C++ version or will it stick with the old Python version?

I wonder if LostMarble and all the folks working on Papagayo forks could be convinced to create a new GitHub organisation for collaborative development of Papagayo across all the groups of people using and modifying Papagayo.

**Comment by pabs3** [comment]
Er, I meant @LostMoho, sorry for the noise @lostmarble.

**Comment by pabs3** [comment]
Hi again, glad to see Morevna and Synfig are still going strong.

Thanks for the info, I guess there is nothing to salvage from the C++
version, except maybe the additional performance from being written in
C++ instead of Python, but that is probably not that useful.

Feel free to close this issue if that is the case.

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by steveway** [comment]
Yeah, I do know C++ but I much prefer Python.
Papagayo-NG has evolved quite a bit over the last few years.
The performance has improved quite a bit recently.
With the new Node System I was able to clean up some rendering hacks and it's smoother on my Test files.
Using C++ might squeeze out more performance in some cases.
The slowest parts currently are the startup of the program, C++ will likely improve that.
And the Autorecognizers using Rhubarb or Allosaurus, but changing to C++ will do nothing here since we are calling external programs which do the work.
Using Python gives us much more flexibility in development.

I doubt the LostMoho People are interested anymore in Papagayo, as Konstantin said, their Repo has been abandoned for years now.
I just saw that Mike Clifton re-acquired his animation software, that's nice.
